import InheritanceClasseImplement;
import InheritanceClasseProtected;
import InheritancePack1.InheritanceClassePrivate;
import InheritanceClassePublic;

public class InheritanceClasseChildren extends InheritanceClasseImplement extends InheritanceClasseProtected extends InheritancePack1.InheritanceClassePrivate extends InheritanceClassePublic {
}
